[package]
name = "textmation"
version = "0.1.0"
authors = ["Christian Vallentin"]
edition = "2018"

[lib]
name = "rasterizer"
crate-type = ["cdylib"]

[dependencies]
image = "0.21.1"

[dependencies.cpython]
version = "0.2"
features = ["extension-module"]
